# Stage 1: Build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app
COPY ./src ./

RUN dotnet restore CustomerApi.LogWorker/CustomerApi.LogWorker.csproj

RUN dotnet publish -c Release -o out CustomerApi.LogWorker/CustomerApi.LogWorker.csproj

# Stage 2: Runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app

RUN adduser --disabled-password --home /appuser appuser
USER appuser

COPY --from=build /app/out ./

ENTRYPOINT ["dotnet", "CustomerApi.LogWorker.dll"]
